export const DEFAULTS = Object.freeze({
    serviceName: "alpacaly-server",
    nodeEnv: "development",
    port: 3000,
    logLevel: "info",
    maxDailyFeeds: 100,
    enforceFeedingWindow: false,
    feedingWindowStart: "08:00",
    feedingWindowEnd: "18:00",
    requestBodyLimit: "16kb",
    corsOrigin: "http://localhost:8000",
    paymentSandboxEnabled: false,
    paymentDonationAmountMinor: 500,
    paymentDonationCurrency: "GBP",
    paymentPublicBaseUrl: "http://localhost:8000",
    paymentProviderTimeoutMs: 10000,
    paymentWebhookToleranceSeconds: 300,
    paymentWebhookBodyLimit: "256kb",
    feedCreditReservationLifetimeMs: 30 * 60 * 1000,
    feedCreditConfirmationTimeoutMs: 60 * 1000,
    feedCreditPresenceTtlMs: 15 * 1000,
    feedCreditReconciliationIntervalMs: 1000,
    centralDatabaseType: "sqlite",
    databasePath: "./data/alpacaly.sqlite",
    postgresPoolMinimum: 0,
    postgresPoolMaximum: 10,
    postgresConnectionTimeoutMs: 5000,
    postgresStatementTimeoutMs: 15000,
    postgresLockTimeoutMs: 5000,
    postgresIdleTransactionTimeoutMs: 15000,
    postgresSslMode: "disable",
    postgresApplicationName: "alpacaly-server",
    recoverySafetyMode: false,
    backupRetentionDailyDays: 14,
    backupRetentionWeeklyWeeks: 8,
    backupRetentionMonthlyMonths: 12,
    backupMinimumRetentionDays: 7,
    backupMaximumAgeHours: 24,
    restoreDrillMaximumAgeDays: 30,
    managedBackupOperationsEnabled: false,
    managedBackupMaximumEvidenceAgeMinutes: 30,
    managedBackupRecoveryPointObjectiveMinutes: 15,
    managedBackupMinimumRetentionDays: 14,
    workerLeaseDurationMs: 30_000,
    workerHeartbeatIntervalMs: 5_000,
    workerStaleThresholdMs: 45_000,
    workerReclaimDelayMs: 1_000,
    workerMaximumClaimDurationMs: 5 * 60_000,
    workerClockSkewToleranceMs: 2_000,
    workerMaximumAttempts: 10,
    enableDevelopmentAuthentication: false,
    managedIdentityProviderConfigured: false,
    supporterAuthProvider: "unconfigured",
    enableDevelopmentSupporterAuthentication: false,
    supporterAuthBaseUrl: "http://localhost:3000",
    supporterPublicReturnUrl: "http://localhost:8000/index.html",
    supporterCsrfSecret: "development-supporter-csrf-secret-not-for-production",
    supporterSessionRollingSeconds: 60 * 60,
    supporterSessionAbsoluteSeconds: 7 * 24 * 60 * 60,
    supporterRecentAuthenticationSeconds: 10 * 60,
    criticalApprovalLifetimeMs: 15 * 60 * 1000,
    outboxPollIntervalMs: 250,
    outboxRetryDelayMs: 1000,
    deviceCommandPollIntervalMs: 100,
    deviceCommandRetryDelayMs: 1000,
    deviceCommandMaximumAttempts: 3,
    deviceAcknowledgementTimeoutMs: 5000,
    deviceTransport: "in_process",
    mqttEnvironment: "development",
    mqttProtocolVersion: 5,
    mqttCommandQos: 1,
    mqttBrokerUrl: "",
    mqttClientId: "alpacaly-server",
    mqttConnectTimeoutMs: 5000,
    mqttReconnectPeriodMs: 1000,
    mqttCommandExpiryMs: 15_000,
    mqttAuthorityLeaseMs: 30_000,
    mqttHeartbeatIntervalMs: 5000,
    mqttStaleThresholdMs: 15_000,
    mqttOfflineThresholdMs: 30_000,
    mqttClockDriftToleranceMs: 2000,
    mqttServerSigningKeyId: "alpacaly-development-server-2026-01",
    mqttControllerSigningKeyId: "alpacaly-development-controller-2026-01",
    simulatedControllerHeartbeatIntervalMs: 5000,
    simulatedControllerHeartbeatTimeoutMs: 15000,
    enableSimulatedControllerConfiguration: true,
    edgeCalibrationVersion: "simulated-calibration-v1",
    edgeWelfareConfigurationVersion: "edge-welfare-v1",
    lifecycleCountdownMs: 10000,
    lifecycleBellMs: 3000,
    lifecycleDispensingMs: 2000,
    lifecycleArchiveDelayMs: 2000
});
