export const PERMISSIONS = Object.freeze({
    VIEW_BARN_STATUS: "VIEW_BARN_STATUS",
    VIEW_FEEDER_STATUS: "VIEW_FEEDER_STATUS",
    VIEW_QUEUES: "VIEW_QUEUES",
    VIEW_COMMAND_HISTORY: "VIEW_COMMAND_HISTORY",
    VIEW_AUDIT_HISTORY: "VIEW_AUDIT_HISTORY",
    PAUSE_FEEDING: "PAUSE_FEEDING",
    SET_WELFARE_UNAVAILABLE: "SET_WELFARE_UNAVAILABLE",
    RECORD_WELFARE_NOTE: "RECORD_WELFARE_NOTE",
    REQUEST_UNCERTAIN_OUTCOME_REVIEW: "REQUEST_UNCERTAIN_OUTCOME_REVIEW",
    PAUSE_DEVICE: "PAUSE_DEVICE",
    SET_MAINTENANCE: "SET_MAINTENANCE",
    INSPECT_COMMAND_FAILURES: "INSPECT_COMMAND_FAILURES",
    REQUEST_COMMAND_RETRY: "REQUEST_COMMAND_RETRY",
    ACKNOWLEDGE_HARDWARE_ALERT: "ACKNOWLEDGE_HARDWARE_ALERT",
    MANAGE_ADMINISTRATORS: "MANAGE_ADMINISTRATORS",
    MANAGE_ROLE_ASSIGNMENTS: "MANAGE_ROLE_ASSIGNMENTS",
    MANAGE_BARN_SCOPES: "MANAGE_BARN_SCOPES",
    MANAGE_SECURITY_CONFIGURATION: "MANAGE_SECURITY_CONFIGURATION",
    DEVELOPMENT_RESET: "DEVELOPMENT_RESET",
    ACTIVATE_EMERGENCY_STOP: "ACTIVATE_EMERGENCY_STOP",
    REQUEST_EMERGENCY_STOP_CLEAR: "REQUEST_EMERGENCY_STOP_CLEAR",
    APPROVE_CRITICAL_ACTION: "APPROVE_CRITICAL_ACTION",
    RESOLVE_UNCERTAIN_OUTCOME: "RESOLVE_UNCERTAIN_OUTCOME",
    REQUEST_REPLACEMENT_COMMAND: "REQUEST_REPLACEMENT_COMMAND"
});

const viewerPermissions = [
    PERMISSIONS.VIEW_BARN_STATUS,
    PERMISSIONS.VIEW_FEEDER_STATUS,
    PERMISSIONS.VIEW_QUEUES,
    PERMISSIONS.VIEW_COMMAND_HISTORY,
    PERMISSIONS.VIEW_AUDIT_HISTORY
];

export const ROLE_PERMISSIONS = Object.freeze({
    VIEWER: Object.freeze([...viewerPermissions]),
    WELFARE_OPERATOR: Object.freeze([
        ...viewerPermissions,
        PERMISSIONS.PAUSE_FEEDING,
        PERMISSIONS.SET_WELFARE_UNAVAILABLE,
        PERMISSIONS.RECORD_WELFARE_NOTE,
        PERMISSIONS.REQUEST_UNCERTAIN_OUTCOME_REVIEW,
        PERMISSIONS.ACTIVATE_EMERGENCY_STOP,
        PERMISSIONS.REQUEST_EMERGENCY_STOP_CLEAR,
        PERMISSIONS.APPROVE_CRITICAL_ACTION,
        PERMISSIONS.RESOLVE_UNCERTAIN_OUTCOME,
        PERMISSIONS.REQUEST_REPLACEMENT_COMMAND
    ]),
    HARDWARE_OPERATOR: Object.freeze([
        ...viewerPermissions,
        PERMISSIONS.PAUSE_DEVICE,
        PERMISSIONS.SET_MAINTENANCE,
        PERMISSIONS.INSPECT_COMMAND_FAILURES,
        PERMISSIONS.REQUEST_COMMAND_RETRY,
        PERMISSIONS.ACKNOWLEDGE_HARDWARE_ALERT,
        PERMISSIONS.ACTIVATE_EMERGENCY_STOP,
        PERMISSIONS.REQUEST_EMERGENCY_STOP_CLEAR,
        PERMISSIONS.APPROVE_CRITICAL_ACTION,
        PERMISSIONS.RESOLVE_UNCERTAIN_OUTCOME,
        PERMISSIONS.REQUEST_REPLACEMENT_COMMAND
    ]),
    ADMINISTRATOR: Object.freeze(Object.values(PERMISSIONS))
});

export const PLATFORM_ONLY_PERMISSIONS = Object.freeze([
    PERMISSIONS.MANAGE_ADMINISTRATORS,
    PERMISSIONS.MANAGE_ROLE_ASSIGNMENTS,
    PERMISSIONS.MANAGE_BARN_SCOPES,
    PERMISSIONS.MANAGE_SECURITY_CONFIGURATION
]);
